### ISSUE TITLE
Won't build in 6.14

### ISSUE THREAD

**Issue by davidwkr** [JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module#233]
`
❯ sudo ./install.sh
make -C /lib/modules/6.14.0-4-cachyos/build M=/home/latte/apps/acer-predator-turbo-and-rgb-keyboard-linux-module-2 modules
make[1]: Entering directory '/usr/lib/modules/6.14.0-4-cachyos/build'
make[2]: Entering directory '/home/latte/apps/acer-predator-turbo-and-rgb-keyboard-linux-module-2'
  CC [M]  src/facer.o
src/facer.c:1181:40: warning: tentative definition of variable with internal linkage has incomplete non-array type 'struct platform_profile_handler' [-Wtentative-definition-incomplete-type]
 1181 | static struct platform_profile_handler platform_profile_handler;
      |                                        ^
src/facer.c:1181:15: note: forward declaration of 'struct platform_profile_handler'
 1181 | static struct platform_profile_handler platform_profile_handler;
      |               ^
src/facer.c:2637:27: error: incomplete definition of type 'struct platform_profile_handler'
 2637 |                 platform_profile_handler.profile_get =
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~^
src/facer.c:1181:15: note: forward declaration of 'struct platform_profile_handler'
 1181 | static struct platform_profile_handler platform_profile_handler;
      |               ^
src/facer.c:2639:27: error: incomplete definition of type 'struct platform_profile_handler'
 2639 |                 platform_profile_handler.profile_set =
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~^
src/facer.c:1181:15: note: forward declaration of 'struct platform_profile_handler'
 1181 | static struct platform_profile_handler platform_profile_handler;
      |               ^
src/facer.c:2643:28: error: incomplete definition of type 'struct platform_profile_handler'
 2643 |                         platform_profile_handler.choices);
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~^
src/facer.c:1181:15: note: forward declaration of 'struct platform_profile_handler'
 1181 | static struct platform_profile_handler platform_profile_handler;
      |               ^
src/facer.c:2645:28: error: incomplete definition of type 'struct platform_profile_handler'
 2645 |                         platform_profile_handler.choices);
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~^
src/facer.c:1181:15: note: forward declaration of 'struct platform_profile_handler'
 1181 | static struct platform_profile_handler platform_profile_handler;
      |               ^
src/facer.c:2647:28: error: incomplete definition of type 'struct platform_profile_handler'
 2647 |                         platform_profile_handler.choices);
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~^
src/facer.c:1181:15: note: forward declaration of 'struct platform_profile_handler'
 1181 | static struct platform_profile_handler platform_profile_handler;
      |               ^
src/facer.c:2649:28: error: incomplete definition of type 'struct platform_profile_handler'
 2649 |                         platform_profile_handler.choices);
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~^
src/facer.c:1181:15: note: forward declaration of 'struct platform_profile_handler'
 1181 | static struct platform_profile_handler platform_profile_handler;
      |               ^
src/facer.c:2651:28: error: incomplete definition of type 'struct platform_profile_handler'
 2651 |                         platform_profile_handler.choices);
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~^
src/facer.c:1181:15: note: forward declaration of 'struct platform_profile_handler'
 1181 | static struct platform_profile_handler platform_profile_handler;
      |               ^
src/facer.c:2653:60: error: too few arguments to function call, expected 4, have 1
 2653 |                 err = platform_profile_register(&platform_profile_handler);
      |                       ~~~~~~~~~~~~~~~~~~~~~~~~~                          ^
/usr/lib/modules/6.14.0-4-cachyos/build/include/linux/platform_profile.h:50:16: note: 'platform_profile_register' declared here
   50 | struct device *platform_profile_register(struct device *dev, const char *name,
      |                ^                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   51 |                                          void *drvdata,
      |                                          ~~~~~~~~~~~~~~
   52 |                                          const struct platform_profile_ops *ops);
      |                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/facer.c:2745:27: error: too few arguments to function call, single argument 'dev' was not specified
 2745 |                 platform_profile_notify();
      |                 ~~~~~~~~~~~~~~~~~~~~~~~ ^
/usr/lib/modules/6.14.0-4-cachyos/build/include/linux/platform_profile.h:58:6: note: 'platform_profile_notify' declared here
   58 | void platform_profile_notify(struct device *dev);
      |      ^                       ~~~~~~~~~~~~~~~~~~
src/facer.c:3349:27: error: too few arguments to function call, single argument 'dev' was not specified
 3349 |                 platform_profile_remove();
      |                 ~~~~~~~~~~~~~~~~~~~~~~~ ^
/usr/lib/modules/6.14.0-4-cachyos/build/include/linux/platform_profile.h:53:5: note: 'platform_profile_remove' declared here
   53 | int platform_profile_remove(struct device *dev);
      |     ^                       ~~~~~~~~~~~~~~~~~~
src/facer.c:3372:27: error: too few arguments to function call, single argument 'dev' was not specified
 3372 |                 platform_profile_remove();
      |                 ~~~~~~~~~~~~~~~~~~~~~~~ ^
/usr/lib/modules/6.14.0-4-cachyos/build/include/linux/platform_profile.h:53:5: note: 'platform_profile_remove' declared here
   53 | int platform_profile_remove(struct device *dev);
      |     ^                       ~~~~~~~~~~~~~~~~~~
src/facer.c:1181:40: error: tentative definition has type 'struct platform_profile_handler' that is never completed
 1181 | static struct platform_profile_handler platform_profile_handler;
      |                                        ^
src/facer.c:1181:15: note: forward declaration of 'struct platform_profile_handler'
 1181 | static struct platform_profile_handler platform_profile_handler;
      |               ^
1 warning and 12 errors generated.
make[4]: *** [/usr/lib/modules/6.14.0-4-cachyos/build/scripts/Makefile.build:207: src/facer.o] Error 1
make[3]: *** [/usr/lib/modules/6.14.0-4-cachyos/build/Makefile:2002: .] Error 2
make[2]: *** [/usr/lib/modules/6.14.0-4-cachyos/build/Makefile:251: __sub-make] Error 2
make[2]: Leaving directory '/home/latte/apps/acer-predator-turbo-and-rgb-keyboard-linux-module-2'
make[1]: *** [Makefile:251: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.14.0-4-cachyos/build'
make: *** [Makefile:18: default] Error 2
rmmod: ERROR: Module acer_wmi is not currently loaded
rmmod: ERROR: Module facer is not currently loaded
insmod: ERROR: could not insert module src/facer.ko: Invalid module format
`

**Comment by LarryTheMagicDragon** [comment]
I've looked into the 6.14 problems already. The new update changes a bunch of things and it requires parts of the module to be rewritten. Currently arch linux has 6.14 in core-testing I was able to temporarily upgrade to try making changes, but my system was a bit bugged so I couldn't compile the modified version. when 6.14 is moved to core and I update through normal channels I'll be able to finish the 6.14 updates. I would update it sooner, but updating to the testing channels made too much of my system unusable. I'll fix this as fast as I can once the arch kernel is updated.

**Comment by LarryTheMagicDragon** [comment]
@davidwkr #226 now has 6.14 fixes. I'm using it on my system without issues and I'm running 6.14.1. Can you let me know if it works for you as well?

**Comment by Pointing8422** [comment]
@LarryTheMagicDragon I tested it on my laptop and it works well

**Comment by LarryTheMagicDragon** [comment]
@Pointing8422 Thanks for letting me know.

**Comment by davidwkr** [comment]
> [@davidwkr](https://github.com/davidwkr) [#226](https://github.com/JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module/pull/226) now has 6.14 fixes. I'm using it on my system without issues and I'm running 6.14.1. Can you let me know if it works for you as well?

I tried with 6.12 lts first (I knew it wouldn't work):
`
❯ sudo ./install.sh
[sudo] password for black:
LTS kernel detected
make -C /lib/modules/6.12.22-1-cachyos-lts/build M=/home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module modules
make[1]: Entering directory '/usr/lib/modules/6.12.22-1-cachyos-lts/build'
  CC [M]  /home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.o
/home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:2804:21: error: variable ‘acer_predator_v4_platform_profile_ops’ has initializer but incomplete type
 2804 | static const struct platform_profile_ops acer_predator_v4_platform_profile_ops = {
      |                     ^~~~~~~~~~~~~~~~~~~~
/home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:2805:10: error: ‘const struct platform_profile_ops’ has no member named ‘probe’
 2805 |         .probe = acer_predator_v4_platform_profile_probe,
      |          ^~~~~
/home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:2805:18: warning: excess elements in struct initializer
 2805 |         .probe = acer_predator_v4_platform_profile_probe,
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:2805:18: note: (near initialization for ‘acer_predator_v4_platform_profile_ops’)
/home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:2806:10: error: ‘const struct platform_profile_ops’ has no member named ‘profile_get’
 2806 |         .profile_get = acer_predator_v4_platform_profile_get,
      |          ^~~~~~~~~~~
/home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:2806:24: warning: excess elements in struct initializer
 2806 |         .profile_get = acer_predator_v4_platform_profile_get,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:2806:24: note: (near initialization for ‘acer_predator_v4_platform_profile_ops’)
/home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:2807:10: error: ‘const struct platform_profile_ops’ has no member named ‘profile_set’
 2807 |         .profile_set = acer_predator_v4_platform_profile_set,
      |          ^~~~~~~~~~~
/home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:2807:24: warning: excess elements in struct initializer
 2807 |         .profile_set = acer_predator_v4_platform_profile_set,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:2807:24: note: (near initialization for ‘acer_predator_v4_platform_profile_ops’)
/home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c: In function ‘acer_platform_profile_setup’:
/home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:2813:43: error: implicit declaration of function ‘devm_platform_profile_register’; did you mean ‘platform_profile_register’? [-Wimplicit-function-declaration]
 2813 |                 platform_profile_device = devm_platform_profile_register(
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                           platform_profile_register
/home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:2813:41: error: assignment to ‘struct device *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 2813 |                 platform_profile_device = devm_platform_profile_register(
      |                                         ^
/home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c: In function ‘acer_thermal_profile_change’:
/home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:2906:17: error: too many arguments to function ‘platform_profile_notify’
 2906 |                 platform_profile_notify(platform_profile_device);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~
/home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:408:6: note: declared here
  408 | void platform_profile_notify()
      |      ^~~~~~~~~~~~~~~~~~~~~~~
/home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c: At top level:
/home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:2804:42: error: storage size of ‘acer_predator_v4_platform_profile_ops’ isn’t known
 2804 | static const struct platform_profile_ops acer_predator_v4_platform_profile_ops = {
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.c:2076:20: warning: ‘WMID_gaming_get_u64’ defined but not used [-Wunused-function]
 2076 | static acpi_status WMID_gaming_get_u64(u64 *value, u32 cap)
      |                    ^~~~~~~~~~~~~~~~~~~
make[3]: *** [scripts/Makefile.build:229: /home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module/src/facer.o] Error 1
make[2]: *** [/usr/lib/modules/6.12.22-1-cachyos-lts/build/Makefile:1952: /home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module] Error 2
make[1]: *** [Makefile:224: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.12.22-1-cachyos-lts/build'
make: *** [Makefile:18: default] Error 2
rmmod: ERROR: Module acer_wmi is not currently loaded
insmod: ERROR: could not insert module src/facer.ko: Invalid module format
[83224.030551] evdi: [I] (card2) Notifying display power state: on
[83241.970757] wlan0: authenticate with dc:36:0c:ac:e8:87 (local address=60:e9:aa:a3:42:71)
[83242.451951] wlan0: send auth to dc:36:0c:ac:e8:87 (try 1/3)
[83242.457063] wlan0: authenticated
[83242.458038] wlan0: associate with dc:36:0c:ac:e8:87 (try 1/3)
[83242.472060] wlan0: RX AssocResp from dc:36:0c:ac:e8:87 (capab=0x1511 status=0 aid=5)
[83242.500980] wlan0: associated
[83242.501053] wlan0: Limiting TX power to 21 (24 - 3) dBm as advertised by dc:36:0c:ac:e8:87
[83329.859519] facer: Acer Laptop WMI Extras unloaded
[83329.907528] facer: version magic '6.6.67-1-cachyos-lts SMP preempt mod_unload ' should be '6.12.22-1-cachyos-lts SMP preempt mod_unload '
[*] Done
`

And tried with 6.14:
`
❯ sudo ./install.sh
[sudo] password for black: 
make -C /lib/modules/6.14.1-2-cachyos/build M=/home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module modules
make[1]: Entering directory '/usr/lib/modules/6.14.1-2-cachyos/build'
make[2]: Entering directory '/home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module'
  CC [M]  src/facer.o
src/facer.c:2076:20: warning: unused function 'WMID_gaming_get_u64' [-Wunused-function]
 2076 | static acpi_status WMID_gaming_get_u64(u64 *value, u32 cap)
      |                    ^~~~~~~~~~~~~~~~~~~
1 warning generated.
  MODPOST Module.symvers
  CC [M]  src/facer.mod.o
  CC [M]  .module-common.o
  LD [M]  src/facer.ko
  BTF [M] src/facer.ko
make[2]: Leaving directory '/home/black/apps/acer-predator-turbo-and-rgb-keyboard-linux-module'
make[1]: Leaving directory '/usr/lib/modules/6.14.1-2-cachyos/build'
if [ -f "/var/lib/shim-signed/mok/MOK.priv" ] && [ -f "/var/lib/shim-signed/mok/MOK.der" ]; then \
        sudo kmodsign sha512 /var/lib/shim-signed/mok/MOK.priv /var/lib/shim-signed/mok/MOK.der src/facer.ko; \
fi
rmmod: ERROR: Module acer_wmi is not currently loaded
rmmod: ERROR: Module facer is not currently loaded
[   22.632885] wlan0: associated
[   22.632962] wlan0: Limiting TX power to 21 (24 - 3) dBm as advertised by dc:36:0c:ac:e8:87
[   26.734125] evdi: [W] evdi_painter_connect:901 (card2) Double connect - replacing 00000000069461f7 with 00000000069461f7
[   26.734130] evdi: [I] (card2) Connected with Task 1081 (DisplayLinkMana) of process 1069 (DisplayLinkMana)
[   26.734134] evdi: [I] (card2) Connector state: connected
[   26.747165] evdi: [I] (card2) Notifying mode changed: 1920x1080@60; bpp 32; pixel format AB24 little-endian (0x34324241)
[   26.747173] evdi: [I] (card2) Notifying display power state: on
[   57.267694] facer: Acer Laptop ACPI-WMI Extras
[   57.267724] facer: Function bitmap for Communication Button: 0x801
[   57.279154] input: Acer WMI hotkeys as /devices/virtual/input/input32
[*] Done
`

Thanks a lot!!!
